name: First Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Get project code
        uses: actions/checkout@v7

      - name: Set up Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'

      - name: Run automated tests
        run: python -m unittest discover -v
      
      - name: Check Python syntax
        run: python -m py_compile result_logic.py test_result_logic.py
      - name: Install coverage
        run: pip install coverage

      - name: Run test coverage
        run: coverage run -m unittest discover -v

      - name: Show coverage report
        run: coverage report
